### ISSUE TITLE
Interface to python

### ISSUE THREAD

**Issue by bonh** [ibaned/omega_h#207]
My python code is based on the python interface of dolfin [https://github.com/FEniCS/dolfin] and I would like to use Omega_h directly from python using some kind of interface.

If you plan an interface, I am willing to contribute.

**Comment by ibaned** [comment]
I think this is a good idea. I have some experience with Python interface, but am not sure exactly how best to do this with DOLFIN. Maybe the first step is to look at the DOLFIN C++-to-Python interface and use that as an example.

**Comment by bonh** [comment]
pybind11 might be a good idea to generate the interface:
[https://www.instapaper.com/read/1014734123]

As I see it, we need interfaces for the following steps (please correct me if I am wrong!):
1. Initialize Omega_h from a mesh. In my case, the mesh comes from dolfin.
2. Transformation between the mesh formats
3. Calculate the metric
4. Adapt

**Comment by ibaned** [comment]
Hi @bonh , I've started to make progress on a Python interface using `pybind11`, which I must say is so far quite straightforward. So far I have only made a very minimal interface for `Omega_h::Comm` and `Omega_h::Library`. See this file for example:

https://github.com/ibaned/omega_h/blob/develop/src/Omega_h_pybind11_comm.cpp

In order to compile this code, one needs to add the following CMake configuration flags:
```bash
-DOmega_h_USE_pybind11:BOOL=ON \
-Dpybind11_PREFIX:PATH="/path/to/pybind11/installation" \
```

The resulting Python module is called `omega_h_pybind11`, and its `PYTHONPATH` is under `src/` in the Omega_h build directory. I'm not yet sure how/where to have CMake install it, but I can load it from the `build/src` directory and the following Python code works:
```python
import omega_h_pybind11
a = omega_h_pybind11.Library()
b = a.world()
b.size()
b.rank()
```

I'll add more interfaces (e.g. `Mesh`) as time allows, but if you would like to contribute some of these interfaces I would welcome that.

**Comment by ibaned** [comment]
@bonh I've made a lot of progress on these interfaces since the last message. The module is now called `PyOmega_h` and the `Library` object is no longer exposed. I have been able to read a Gmsh file and adapt it from Python. Testing of the DOLFIN interface through Python is next, but a draft is there. The interface is fairly consistent with your pull request, so I believe we are on the right path.

**Comment by ibaned** [comment]
PS - all this recent progress is in the develop branch.

**Comment by bonh** [comment]
Wow, you are working faster than I can follow up :smile:

**Comment by bonh** [comment]
@ibaned I noticed from your last commit, that you are running into problems from dolfin's swig stuff too. The guys working on FEniCS are currently porting the software to use pybind11 - so perhaps we should work with their pybind11 branch or wait for the 2018.1 release of FEniCS. (https://bitbucket.org/fenics-project/dolfin/issues/897/switch-from-swig-to-pybind11-for-python) (https://hub.docker.com/r/fenicsproject/pybind11-testing/)

**Comment by bonh** [comment]
Mhh, I am not finding a docker with a running pybind11 interface at the moment. The pybind11-testing seems to be abandoned. Perhaps in the dev branch...

**Comment by ibaned** [comment]
I see pybind11 code in the DOLFIN `master` branch. I asked the FEniCS Slack channel about this.

**Comment by ibaned** [comment]
Drew Parsons confirms that FEniCS version 2018.1 will use `pybind11`. I may have to compile DOLFIN from source until then, which has been tricky in the past.

**Comment by bonh** [comment]
This one looks like a official master branch build: https://quay.io/repository/fenicsproject/dev . Not tested yet.

**Comment by bonh** [comment]
I checked out the docker and worked with the demo_poisson.py. Seems to be the right direction

**Comment by ibaned** [comment]
@bonh thank you for pointing out the Docker build of the current master branch!  Using that build, I was able to complete the Python interface for the Poisson problem. Please see the latest `omega_h` and `omega_h-dolfin` repositories, you should be able to run `demo_poisson.py` in serial now. I haven't tried parallel yet.

**Comment by bonh** [comment]
I can confirm, that it works in serial. But something is missing to make it work in parallel. Not sure about the source of the error yet...will report more details at the end of the week (hopefully...).

**Comment by ibaned** [comment]
@bonh I'm not sure if the DOLFIN to Omega_h conversion works right in parallel. It is preferrable to construct the mesh in Omega_h and copy to DOLFIN instead of vice versa.

**Comment by bonh** [comment]
@ibaned You are right - it works in parallel if the mesh is constructed in Omega_h and this should not be a larger issue for my code. 

I adapted the demo_poisson.py to make it work in parallel.

**Comment by bonh** [comment]
@ibaned Well, the interface seems to be working. I have not tested the interface within my code and on more than 4 cores yet. Nevertheless, I propose, that we close this issue and open up more specific issues for new bugs and enhancements.

**Comment by ibaned** [comment]
@bonh that sounds great, thanks! Feel free to submit a pull request for your modified Python code. Also feel free to open more issues for future enhancements.

**Comment by bonh** [comment]
Note the pull request #5 in omega_h-dolfin.
