### ISSUE TITLE
Metric with multiple fields as input

### ISSUE THREAD

**Issue by bonh** [ibaned/omega_h#215]
In coupled problems, different solution variables, e.g., pressure and velocity, influence the grid requirements. Is it possible, to allow for metrics which depend on a many solution fields?

**Comment by bgranzow** [comment]
As a quick answer until @ibaned can elaborate, I think the answer is almost certainly yes, because I've done it before. I used Omega_h's YAML parameter list interface to drive an adaptive example with two metric sources, as seen [here](https://github.com/bgranzow/anisovms/blob/master/ex1_adapt.yaml). I'm pretty sure the `Sources` parameter list in this block of parameters fills in [this](https://github.com/ibaned/omega_h/blob/master/src/Omega_h_adapt.hpp#L97) data inside the `MetricInput` struct

**Comment by ibaned** [comment]
@bonh from the Python perspective, something like this should work:

```python
    pressure_source = omega_h.MetricSource(omega_h.VARIATION, 2e-3, "pressure")
    velocity_source = omega_h.MetricSource(omega_h.VARIATION, 2e-3, "velocity")
    metric_input = omega_h.MetricInput()
    metric_input.add_source(pressure_source)
    metric_input.add_source(velocity_source)
```

**Comment by ibaned** [comment]
I'll close this assuming that answer works for you. If not, please comment here.
Thanks!

**Comment by bonh** [comment]
@bgranzow @ibaned Works! And thanks for the quick reply!
