### ISSUE TITLE
Metric approach has stalled with minimum quality 0.173261 < 0.3

### ISSUE THREAD

**Issue by bonh** [ibaned/omega_h#235]
Hi @ibaned ,

do you have a pointer what I can do if the following error pops up?

```
Metric approach has stalled with minimum quality 0.173261 < 0.3
Decreasing "Min Quality Allowed" may help, but otherwise the metric is likely not satisfiable
Metric approach has stalled at step size = 0.000061 < 0.000100.
```
Henning

**Comment by bonh** [comment]
Additionally: Which exception is thrown in omega_h if this happens? I would like to catch it in python. The C++ exceptions are automatically translated to python (?), see <http://pybind11.readthedocs.io/en/stable/advanced/exceptions.html>.

**Comment by ibaned** [comment]
1. There is something about the metric and domain that prevent a solution which satisfies both edge lengths and quality. This usually means a metric field has high gradation, Omega_h has code for limiting metric gradation that should be used to pre-process the metric. It can also be a more subtle aspect related to the geometry, or the rate at which the metric is approached. If simple things like gradation limiting don't help, we will likely have to look at the problem together.

2. Right now Omega_h calls `abort()` instead of throwing exceptions, because it is much easier to get a stack trace from a signal handler than from an exception, especially on large parallel machines. I can add an option to instead throw an exception.

**Comment by bonh** [comment]
On 1.
I added a python binding for min_quality_allowed (should I add a pull request?) and set it to a low value. After a few iterations, the quality goes up again. So I assume, that the physical initial conditions are somewhat poor.

On 2.
Throwing an exception in Omega_h would allow me to catch it and gracefully terminate my program. So yes, it would be great if you could add an exception, thx!

**Comment by ibaned** [comment]
1. Thank you for that, yes please add a pull request if you can.

2. In the develop branch there is a new option `-DOmega_h_THROW:BOOL=ON`, which will throw an exception. I'd like to combine this with the pull request for (1) and release a new Omega_h version.

**Comment by bonh** [comment]
Thx!
